### ISSUE TITLE
adopt udnssdk

### ISSUE THREAD

**Issue by josephholsten** [terra-farm/meta#1]
https://github.com/Ensighten/udnssdk

**Comment by josephholsten** [comment]
cf https://github.com/Ensighten/udnssdk/issues/65

**Comment by rowleyaj** [comment]
@josephholsten there is an ultradns org on github which has the SDK's in ruby as well as some sample API clients in various languages. They don't look like they've been updated since 2014 though :(

Is it worth reaching out to someone from https://github.com/orgs/ultradns/people to see if they want to maintain this as part of terra-farm? They might be able to provide insight into any upcoming API changes as well.

**Comment by rowleyaj** [comment]
This has been moved to the org. Closing this issue.
