### ISSUE TITLE
talk with ccll/virtualbox 

### ISSUE THREAD

**Issue by josephholsten** [terra-farm/meta#3]
https://github.com/ccll/terraform-provider-virtualbox

**Comment by nbering** [comment]
I used this provider to figure out how to write non-core providers. The binary releases attached to the project are broken for the current version because it was built against an out-of-date plugin protocol. It can be rebuilt against new versions and as far as I know it still works.

The project's readme says it is looking for a maintainer. It looks like there's actually been some activity in the last month, for the first time in over a year.

**Comment by josephholsten** [comment]
cf https://github.com/ccll/terraform-provider-virtualbox/issues/10

**Comment by ringods** [comment]
@josephholsten the virtualbox provider is transferred, so this issue can be closed.

**Comment by ringods** [comment]
The `go-virtualbox` SDK used in the `virtualbox` provider will also be migrated to this organization:

https://github.com/riobard/go-virtualbox/issues/6
